name: Code Analysis

on:
  pull_request: null
  push:
    branches:
      - develop-v1
  workflow_dispatch:
permissions:
  contents: read
jobs:
  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: 'PHPStan'
            run: composer phpstan
          - name: 'Coding Standards'
            run: composer fix-cs
    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # see https://github.com/php-actions/composer
      - uses: php-actions/composer@v6
        with:
          php-version: 8.2
      - run: ${{ matrix.actions.run }}
